import { create } from 'zustand';
import { useAppStore } from '../store/useAppStore';

/** Offline status shown to the user ("Available offline" once everything is cached). */
interface PwaState {
  offlineReady: boolean;
  setOfflineReady: (ready: boolean) => void;
}

export const usePwaStore = create<PwaState>((set) => ({
  offlineReady: false,
  setOfflineReady: (offlineReady) => set({ offlineReady }),
}));

const RELOAD_FLAG = 'logmath-coi-reload';

/**
 * Registers dist/sw.js (generated by scripts/build-sw.mjs) in production builds.
 * The worker precaches the app, the ONNX Runtime and the model, so the app works
 * in airplane mode after one online visit.
 */
export function registerServiceWorker(): void {
  if (!import.meta.env.PROD || !('serviceWorker' in navigator)) return;

  window.addEventListener('load', () => {
    const base = import.meta.env.BASE_URL;
    const firstInstall = !navigator.serviceWorker.controller;

    navigator.serviceWorker
      .register(`${base}sw.js`, { scope: base })
      .then(() => navigator.serviceWorker.ready)
      .then(() => {
        // `ready` resolves once the worker is active, i.e. after the precache finished.
        usePwaStore.getState().setOfflineReady(true);
      })
      .catch((error: unknown) => {
        console.warn('[logmath] service worker registration failed; the app still works online', error);
      });

    // Hosts that can't send COOP/COEP headers (GitHub Pages): the service worker adds
    // them, but only to pages it controls. Reload once after the first install so the
    // page becomes cross-origin isolated (multi-threaded WASM) — only if nothing has
    // been drawn yet, so no work is lost. Otherwise the next visit picks it up.
    if (firstInstall && !window.crossOriginIsolated) {
      navigator.serviceWorker.addEventListener(
        'controllerchange',
        () => {
          let reloaded = false;
          try {
            reloaded = sessionStorage.getItem(RELOAD_FLAG) === '1';
            sessionStorage.setItem(RELOAD_FLAG, '1');
          } catch {
            reloaded = true; // storage blocked: never risk a reload loop
          }
          if (!reloaded && useAppStore.getState().strokes.length === 0) window.location.reload();
        },
        { once: true },
      );
    }
  });
}
